name: pull request comment
on:
  pull_request:
    branches: [ "main" ]
  issue_comment:
    types: [created, deleted]
jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    #if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, 'build now')
    if: contains(github.event.comment.body, 'build now')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on: PR $NUMBER \n Body of the comment: $COMMENT
    env:
        NUMBER: ${{ github.event.issue.number }}
        COMMENT: ${{ github.event.comment.body }}
  jenkins_trigger:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest
    steps:
      - name: Trigger your-job
        uses: appleboy/jenkins-action@master
        with:
          url: "https://8422-2406-7400-43-2c91-fbde-9005-8fc9-54fe.in.ngrok.io"
          user: ${{ secrets.JENKINS_USER }}
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "Jenkins-Github-action"
